version: '3.8'
services:
  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mdp
      MYSQL_DATABASE: bdd_cleanify
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: mdp
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
volumes:
  db_data:
